# Base configs
baseurl: "https://nthere.dev/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Nrupatunga"
subtitle: "Nature is Beautiful"
author: "Nrupatunga"
header:
 title: "Photography"
 subtitle: "by Nrupatunga"
footer:
 name: "Hey there, my name is Nrupatunga"
 bio: "I am a software engineer from India, I love nature, birds."
web_design: "AJ"
social_urls:
  twitter: "https://twitter.com/nrupatunga1987"
  github: "https://www.github.com/nrupatunga"
